add_newline = false

format = """
$hostname${custom.ip_info}$time⇒ $directory
[ ](bright-green) $username$character
"""

[time]
disabled = false
format = "[  ]($style)[$time]($style) "
time_format = "%Y-%m-%d %H:%M"
style = "yellow"

[username]
show_always = true
format = "[$user]($style) "
style_user = "bright-blue"
style_root = "red bold"

[hostname]
ssh_only = false
format = "[  ](bright-blue)[  $hostname ]($style)"
style = "green"

[directory]
truncation_length = 3
style = "purple"
read_only = '🔒'
read_only_style = 'red'
home_symbol = '~'

[character]
success_symbol = "[❯](green)[❯](bright-green)"
error_symbol = "[❯](red)[❯](bright-red)"

[custom.ip_info]
command = '''
ip=$(hostname -I | awk '{print $1}')
if [[ $ip == 127.* || $ip == 10.* || $ip == 192.168.* || $ip == 172.1[6-9].* || $ip == 172.2[0-9].* || $ip == 172.3[0-1].* ]]; then
    printf "🏠 \x1b[1;33m(%s)\x1b[0m" "$ip"
else
    printf "🌐 \x1b[31m(%s)\x1b[0m" "$ip"
fi
'''
when = "true"
format = "[$output](none) "
