#!/usr/bin/env bash

# evitar anidar tmux
[ -n "$TMUX" ] && exit 0

SESSION="main"

if ! tmux has-session -t "$SESSION" 2>/dev/null; then
	tmux new-session -d -s "$SESSION" -n local
	tmux new-window -t "$SESSION":2 -n remote
	tmux select-window -t "$SESSION":1
fi

exec tmux attach-session -t "$SESSION"
